# Top-level entries
path = "inverse_velocity/data/"

# Optimization sub-table
[optimization]
niteration = 30
inverse_timestep_range = [300, 380]
checkpoint_interval = 1
lr = 0.1
initial_velocities = [[0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0]]

# Ground Truth sub-table
[ground_truth]
ground_truth_npz = "ground_truth.npz"
ground_truth_mpm_inputfile = "mpm_input.json"

# Forward Simulator sub-table
[forward_simulator]
dt_mpm = 0.0025
model_path = "inverse_velocity/data/"
model_file = "model.pt"
simulator_metadata_path = "inverse_velocity/data/"
simulator_metadata_file = "gns_metadata.json"

# Resume sub-table
[resume]
resume = false
iteration = 1

# Output sub-table
[output]
output_dir = "inverse_velocity/data/outputs/"
save_step = 1

